force-app/main/default/objects/User_Profile__c/User_Profile__c.object-meta.xml
<CustomObject>
    <description>Information for the related contact to login</description>
    <label>User_Profile</label>
    <nameField>
        <label>User_Profile Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>User_Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Profile__c/fields/Contact_User__c.field-meta.xml
<CustomField>
    <fullName>Contact_User__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Contact the the user profile is related to</description>
    <label>Contact_User</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>User_Profiles</relationshipLabel>
    <relationshipName>User_Profiles</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User_Profile__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>eMail address for the user profile of the contact</description>
    <inlineHelpText>eMail must match the eMail of the contact related to this user profile.</inlineHelpText>
    <label>Email</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/User_Profile__c/fields/Password__c.field-meta.xml
<CustomField>
    <fullName>Password__c</fullName>
    <description>Password for the user profile</description>
    <inlineHelpText>Must follow guideline of including one letter, one number, and must be more than eight characters long.</inlineHelpText>
    <label>Password</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/User_Profile__c/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <description>Phone number of user profile</description>
    <inlineHelpText>Phone number of contact associated with this user profile.</inlineHelpText>
    <label>Phone</label>
    <required>true</required>
    <type>Phone</type>
</CustomField>

force-app/main/default/classes/LoginPageController.cls
//David D'Alessandro
//12/27/21
//Login Page controller

public with sharing class LoginPageController {
    
    @AuraEnabled(cacheable=true)
    public static User_Profile__c authenticateLogin(String userName, String password){
        List<User_Profile__c> user = [SELECT name, email__c, phone__c, Contact_User__r.AccountId FROM User_Profile__c WHERE name = :userName AND password__c = :password];

        if(user.size() > 0){
            return user[0];
        }
        else{
            return null;
        }
    }

}