force-app/main/default/objects/User_Profile__c/User_Profile__c.object-meta.xml
<CustomObject>
    <description>Information for the related contact to login</description>
    <label>User_Profile</label>
    <nameField>
        <label>User_Profile Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>User_Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Profile__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>eMail address for the user profile of the contact</description>
    <inlineHelpText>eMail must match the eMail of the contact related to this user profile.</inlineHelpText>
    <label>Email</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

force-app/main/default/classes/User_ProfileTiggerHelper.cls
//David D'Alessandro
//12/28/21
//User_Profile Trigger Helper

public with sharing class User_ProfileTiggerHelper {
    public User_ProfileTiggerHelper() {
        system.debug('hello');
    }

    //User_ProfileValidateDuplicate
    //ensure no profile is created with the same name or email
    public static void User_ProfileValidateDuplicate(List<User_Profile__c> newUser_Profiles){
        
        //query for all current user profile names and emails
        List<User_Profile__c> currUser_Profiles = [SELECT Name, email__c FROM User_Profile__c];

        //loop through the new profiles
        for(User_Profile__c newUser_Profile : newUser_Profiles){

        }//end for newUser_Profiles



    }



}