force-app/main/default/objects/User_Profile__c/User_Profile__c.object-meta.xml
<CustomObject>
    <description>Information for the related contact to login</description>
    <label>User_Profile</label>
    <nameField>
        <label>User_Profile Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>User_Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Profile__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>eMail address for the user profile of the contact</description>
    <inlineHelpText>eMail must match the eMail of the contact related to this user profile.</inlineHelpText>
    <label>Email</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/User_Profile__c/fields/Password__c.field-meta.xml
<CustomField>
    <fullName>Password__c</fullName>
    <description>Password for the user profile</description>
    <inlineHelpText>Must follow guideline of including one letter, one number, and must be more than eight characters long.</inlineHelpText>
    <label>Password</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/User_Profile__c/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <description>Phone number of user profile</description>
    <inlineHelpText>Phone number of contact associated with this user profile.</inlineHelpText>
    <label>Phone</label>
    <required>true</required>
    <type>Phone</type>
</CustomField>

force-app/main/default/classes/DataFactory.cls
//David D'Alessandro
//12/22/21
//Data factory for all necessary pieces of data

public with sharing class DataFactory {
    
    //----------------Accounts--------------------//
     //CreateAccountEmpty (Single)
     //creates a single empty account
     public static Account CreateAccountEmpty(){

        Account newAccount = new Account();

        return newAccount;

    }//end CreateAccountEmpty (Single)
    
    //CreateAccountEmpty (Multiple)
    //creates multiple empty accounts
    public static List<Account> CreateAccountEmpty(Integer numAccounts){

        List<Account> newAccounts = new List<Account>();

        for(Integer i = 0; i < numAccounts; i++){
            newAccounts.add(new Account());
        }//end for i

        return newAccounts;

    }//end CreateAccountEmpty (Multiple)

   
    //----------------User_Profiles----------------//

    //----------------Empty Profiles---------------//
    //CreateUser_Profile (Single)
    //creates a single empty user_profile
    public static User_Profile__c CreateUser_ProfileEmpty(){
        User_Profile__c newUser_Profile = new User_Profile__c();

        return newUser_Profile;
    }// CreateUser_ProfileEmpty

    //CreateUser_ProfileEmpty (Multiple)
    //creates multiple empty user_profiles
    public static List<User_Profile__c> CreateUser_ProfileEmpty(Integer numUser_Profiles){
        
        List<User_Profile__c> newUser_Profiles = new List<User_Profile__c>();

        for(Integer i = 0; i < numUser_Profiles; i++){
            newUser_Profiles.add(new User_Profile__c());
        }//end for i

        return newUser_Profiles;
    }

    //----------------Filled Profiles---------------//
    //CreateUser_ProfileFilled (single)
    //creates a single filled user_profile
    public static User_Profile__c CreateUser_ProfileFilled(){
        User_Profile__c newUser_Profile = new User_Profile__c(Name = 'Test', password__c = 'password', email__c = 'email@email.com', phone__c = ' (666) 666 6666');

        return newUser_Profile;
    }

    //CreateUser_ProfileFilled (multiple)
    //creates multiple filled user_profiles with unique names
    public static List<User_Profile__c> CreateUser_ProfileFilled(Integer numUser_Profiles){

        List<User_Profile__c> newUser_Profiles = new List<User_Profile__c>();
        String user_Name = '';
        String test = 'Test';
        String index = '';

        for(Integer i = 0; i < numUser_Profiles; i++){
            index = String.valueOf(i+1);
            user_Name = test + index;
            newUser_Profiles.add(new User_Profile__c(Name = user_Name, password__c = 'password', email__c = 'email@email.com', phone__c = ' (666) 666 6666'));
        }//end for i

        return newUser_Profiles;

    }

}